/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsusario;

import LogicaAplicacion.Mapa;
import LogicaAplicacion.MapaCalor;
import LogicaAplicacion.ThreadSimulacion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JTextField;

/**
 *
 * @author Cristian
 */
public class VentanaAnimacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaAnimacion
     */
    private Mapa mapaAmbiente;
    private MapaCalor mapaCalor;
    private ButtonGroup grupoBotones = new ButtonGroup();
    private static VentanaAnimacion ventanaAnimacion;
    private ThreadSimulacion threadSimulacion;
    
    private VentanaAnimacion() {
        initComponents();
        grupoBotones.add(botonPausar);
        grupoBotones.add(botonIniciar);
        this.mapaAmbiente=new Mapa();
        this.panelAgentes.add(mapaAmbiente);
        this.mapaCalor=new MapaCalor();
        this.panelMapaCalor.add(mapaCalor);
        
    }
    
    public static VentanaAnimacion getVentanaAnimacion(){
        if(ventanaAnimacion==null){
            ventanaAnimacion=new VentanaAnimacion();
        }
        return(ventanaAnimacion);
    }
    
    public Mapa getMapa(){
        return(mapaAmbiente);
    }
    
    public MapaCalor getMapaCalor(){
        return(mapaCalor);
    }
    
    public ThreadSimulacion getThreadSimulacion() {
        if(this.threadSimulacion==null){
            return (null);
        }
        return this.threadSimulacion;
    }

    public void setThreadSimulacion(ThreadSimulacion threadSimulacion) {
        this.threadSimulacion = threadSimulacion;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        botonIniciar = new javax.swing.JToggleButton();
        botonPausar = new javax.swing.JToggleButton();
        botonDetener = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        textPasoTiempo = new javax.swing.JTextField();
        etiqueta = new javax.swing.JLabel();
        textSubPasoTiempo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        botonVolver = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAgentes = new java.awt.ScrollPane();
        panelMapaCalor = new java.awt.ScrollPane();

        setTitle("Animación");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/AC3D.png"))); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(131591, 32769));
        jToolBar1.setMinimumSize(new java.awt.Dimension(678, 31));
        jToolBar1.setPreferredSize(new java.awt.Dimension(678, 31));

        botonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/playc.png"))); // NOI18N
        botonIniciar.setText("Iniciar");
        botonIniciar.setFocusable(false);
        botonIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonIniciar.setMaximumSize(new java.awt.Dimension(129, 29));
        botonIniciar.setMinimumSize(new java.awt.Dimension(129, 29));
        botonIniciar.setPreferredSize(new java.awt.Dimension(129, 29));
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        jToolBar1.add(botonIniciar);

        botonPausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Pausec.png"))); // NOI18N
        botonPausar.setText("Pausar");
        botonPausar.setFocusable(false);
        botonPausar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonPausar.setMaximumSize(new java.awt.Dimension(129, 29));
        botonPausar.setMinimumSize(new java.awt.Dimension(129, 29));
        botonPausar.setPreferredSize(new java.awt.Dimension(129, 29));
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        jToolBar1.add(botonPausar);

        botonDetener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/stopc.png"))); // NOI18N
        botonDetener.setText("Detener/Reiniciar");
        botonDetener.setFocusable(false);
        botonDetener.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonDetener.setMaximumSize(new java.awt.Dimension(129, 29));
        botonDetener.setMinimumSize(new java.awt.Dimension(129, 29));
        botonDetener.setPreferredSize(new java.awt.Dimension(129, 29));
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        jToolBar1.add(botonDetener);
        jToolBar1.add(jSeparator2);

        jLabel1.setText("  Paso de Tiempo ");
        jToolBar1.add(jLabel1);

        textPasoTiempo.setEditable(false);
        textPasoTiempo.setBackground(new java.awt.Color(255, 255, 255));
        textPasoTiempo.setMaximumSize(new java.awt.Dimension(50, 20));
        textPasoTiempo.setMinimumSize(new java.awt.Dimension(50, 20));
        textPasoTiempo.setPreferredSize(new java.awt.Dimension(50, 20));
        jToolBar1.add(textPasoTiempo);

        etiqueta.setText("      Sub Paso de Tiempo ");
        jToolBar1.add(etiqueta);

        textSubPasoTiempo.setEditable(false);
        textSubPasoTiempo.setBackground(new java.awt.Color(255, 255, 255));
        textSubPasoTiempo.setMaximumSize(new java.awt.Dimension(50, 20));
        textSubPasoTiempo.setMinimumSize(new java.awt.Dimension(50, 20));
        textSubPasoTiempo.setPreferredSize(new java.awt.Dimension(50, 20));
        jToolBar1.add(textSubPasoTiempo);
        jToolBar1.add(jSeparator3);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/volverChico.png"))); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.setFocusable(false);
        botonVolver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonVolver.setMaximumSize(new java.awt.Dimension(80, 29));
        botonVolver.setMinimumSize(new java.awt.Dimension(80, 29));
        botonVolver.setPreferredSize(new java.awt.Dimension(80, 29));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jToolBar1.add(botonVolver);

        jTabbedPane1.addTab("Agentes", panelAgentes);
        jTabbedPane1.addTab("Mapa de Calor", panelMapaCalor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        if(VentanaAnimacion.getVentanaAnimacion().getThreadSimulacion()!=null){
            try {
                VentanaAnimacion.getVentanaAnimacion().getThreadSimulacion().parar();
                VentanaAnimacion.getVentanaAnimacion().getThreadSimulacion().join();
                VentanaAnimacion.getVentanaAnimacion().setThreadSimulacion(null);
            } catch (InterruptedException ex) {
                Logger.getLogger(VentanaAnimacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        VentanaPrincipal.getVentanaPrincipal().setEstadoMenuPrincipal(true,true,true);
        this.dispose();
        ventanaAnimacion=null;
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        // TODO add your handling code here:
        if(this.getThreadSimulacion()==null){
            ThreadSimulacion threadSimulacion = new ThreadSimulacion(1, 0);
            VentanaAnimacion.getVentanaAnimacion().setThreadSimulacion(threadSimulacion);
            VentanaAnimacion.getVentanaAnimacion().getThreadSimulacion().start();
        }
        else{
            this.getThreadSimulacion().reiniciar();
        }
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        // TODO add your handling code here:
        if(VentanaAnimacion.getVentanaAnimacion().getThreadSimulacion()!=null){      
            try {
                VentanaAnimacion.getVentanaAnimacion().getThreadSimulacion().parar();
                VentanaAnimacion.getVentanaAnimacion().getThreadSimulacion().join();
                this.panelAgentes.removeAll();
                this.panelMapaCalor.removeAll();
                VentanaAnimacion.getVentanaAnimacion().setThreadSimulacion(null);
                this.mapaAmbiente=null;
                this.mapaAmbiente=new Mapa();
                this.panelAgentes.add(mapaAmbiente);
                this.mapaAmbiente.paint(this.mapaAmbiente.getGraphics());
                this.mapaCalor=null;
                this.mapaCalor=new MapaCalor();
                this.panelMapaCalor.add(mapaCalor);
                this.mapaCalor.paint(this.mapaCalor.getGraphics());
                this.paintAll(this.getGraphics());
            } catch (InterruptedException ex) {
                Logger.getLogger(VentanaAnimacion.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_botonDetenerActionPerformed

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        // TODO add your handling code here:
        this.getThreadSimulacion().pausar();
    }//GEN-LAST:event_botonPausarActionPerformed

    public JTextField getTextPasoTiempo() {
        return textPasoTiempo;
    }

    public JTextField getTextSubPasoTiempo() {
        return textSubPasoTiempo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDetener;
    private javax.swing.JToggleButton botonIniciar;
    private javax.swing.JToggleButton botonPausar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.ScrollPane panelAgentes;
    private java.awt.ScrollPane panelMapaCalor;
    private javax.swing.JTextField textPasoTiempo;
    private javax.swing.JTextField textSubPasoTiempo;
    // End of variables declaration//GEN-END:variables
}
