/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsusario;

import LogicaAplicacion.AutomataCelular;
import LogicaAplicacion.Proyecto;
import LogicaAplicacion.Utilidades;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class VentanaConfiguracionGeneral extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaConfiguracionGeneral
     */
    private static VentanaConfiguracionGeneral ventanaConfiguracionGeneral;  
    
    private VentanaConfiguracionGeneral() {
        initComponents();
        actualizarCamposVentana();
    }

    public static VentanaConfiguracionGeneral getVentanaconfiguracionGeneral(){
        if(ventanaConfiguracionGeneral==null){
            ventanaConfiguracionGeneral=new VentanaConfiguracionGeneral();
        }   
        return ventanaConfiguracionGeneral;
    }
    
    private void actualizarCamposVentana(){
        this.textNombreProyecto.setText(Proyecto.getProyecto().getNombreProyecto());
        if(Proyecto.getProyecto().getProyectoValido()==0){ //PROYECTO NO VALIDO
            labelValido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ballred.png"))); // NOI18N
        }
        else{
            labelValido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ballGreen.png")));
        }
        this.textAnchoX.setText(Integer.toString(Proyecto.getProyecto().getTamañox()));
        this.textAltoY.setText(Integer.toString(Proyecto.getProyecto().getTamañoy()));
        this.textNotas.setText(Proyecto.getProyecto().getNotasProyecto());
        
        //CRISTIAN 07/08/2018 Comentado porque saque los combos
        //this.comboFuego.setSelectedIndex(Proyecto.getProyecto().getPropagacionFuego()-1);
        //this.comboHumo.setSelectedIndex(Proyecto.getProyecto().getPropagacionHumo()-1);
        this.comboVelMinima.setSelectedIndex(Proyecto.getProyecto().getVelocidadMinima()-1);
        this.comboVelMaxima.setSelectedIndex(Proyecto.getProyecto().getVelocidadMaxima()-1);
        this.textReaccionMinima.setText( Integer.toString(Proyecto.getProyecto().getTiempoReaccionMinimo()));
        this.textReaccionMaxima.setText( Integer.toString(Proyecto.getProyecto().getTiempoReaccionMaximo()));


        
        this.textPersonas.setText(Integer.toString(Proyecto.getProyecto().getCantidadPersonas()));
        
        //COMENTADO PORQUE BORRE EL TEXTSALIDA
        //this.textSalidas.setText(Integer.toString(Proyecto.getProyecto().getCantidadSalidas()));
        /*if(Proyecto.getProyecto().getSalidas().size()<=0){
            this.textSalidas.setText("0"); 
        }
        else{ 
           Utilidades.construirSalidas();
           this.textSalidas.setText(Integer.toString(Proyecto.getProyecto().getSalidas().size()));
        }*/
     }
    
    
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        botonAceptar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textNombreProyecto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textAnchoX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textAltoY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textNotas = new javax.swing.JTextArea();
        textPersonas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboVelMinima = new javax.swing.JComboBox<>();
        comboVelMaxima = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        labelVel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelRea = new javax.swing.JLabel();
        textReaccionMinima = new javax.swing.JTextField();
        labelReaccion = new javax.swing.JLabel();
        textReaccionMaxima = new javax.swing.JTextField();
        labelValido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximizable(true);
        setResizable(true);
        setTitle("Propiedades del Proyecto");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/AC3D.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(1881, 1260));
        setMinimumSize(new java.awt.Dimension(627, 420));
        setPreferredSize(new java.awt.Dimension(627, 420));

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.add(filler2);

        botonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/aceptarChico.png"))); // NOI18N
        botonAceptar.setText("Guardar");
        botonAceptar.setFocusable(false);
        botonAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonAceptar.setMaximumSize(new java.awt.Dimension(100, 35));
        botonAceptar.setMinimumSize(new java.awt.Dimension(100, 35));
        botonAceptar.setPreferredSize(new java.awt.Dimension(100, 35));
        botonAceptar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        jToolBar1.add(botonAceptar);

        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/volverChico.png"))); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.setFocusable(false);
        botonVolver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botonVolver.setMaximumSize(new java.awt.Dimension(100, 35));
        botonVolver.setMinimumSize(new java.awt.Dimension(100, 35));
        botonVolver.setPreferredSize(new java.awt.Dimension(100, 35));
        botonVolver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jToolBar1.add(botonVolver);

        jLabel1.setText("Nombre del Proyecto");

        jLabel3.setText("Ancho (X)");

        jLabel4.setText("Largo (Y)");

        jLabel8.setText("Notas");

        textNotas.setColumns(20);
        textNotas.setRows(5);
        jScrollPane2.setViewportView(textNotas);

        textPersonas.setEditable(false);
        textPersonas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Personas");

        jLabel5.setText("Velocidad");

        comboVelMinima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.4", "0.8", "1.2", "1.6", "2.0", "2.4", "2.8", "3.2", "3.6", "4.0" }));

        comboVelMaxima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.4", "0.8", "1.2", "1.6", "2.0", "2.4", "2.8", "3.2", "3.6", "4.0" }));

        jLabel6.setText("Mínima");

        labelVel.setText("Máxima");

        jLabel9.setText("Tiempo de Reacción");

        labelRea.setText("Mínimo");

        labelReaccion.setText("Máximo");

        labelValido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ballGreen.png"))); // NOI18N
        labelValido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Proyecto Validado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelValido)
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textAnchoX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAltoY, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textNombreProyecto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(comboVelMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelRea)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textReaccionMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(labelReaccion)
                                        .addGap(71, 71, 71))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(labelVel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textReaccionMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboVelMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 122, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textAltoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textAnchoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addComponent(labelValido))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(comboVelMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelRea)
                            .addComponent(textReaccionMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboVelMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelVel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelReaccion)
                            .addComponent(textReaccionMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal.getVentanaPrincipal().setEstadoMenuPrincipal(true,true,true);
        this.dispose();
        ventanaConfiguracionGeneral=null;
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        try{
            int guardarCambios=0;
            boolean redimensionarProyecto=false;
            int tamañox = Integer.parseInt(this.textAnchoX.getText().trim());
            int tamañoy = Integer.parseInt(this.textAltoY.getText().trim());
            //CRISTIAN 07/08/2018
            Proyecto.getProyecto().setVelocidadMinima(this.comboVelMinima.getSelectedIndex()+1);
            Proyecto.getProyecto().setVelocidadMaxima(this.comboVelMaxima.getSelectedIndex()+1);
            Proyecto.getProyecto().setTiempoReaccionMinimo(Integer.parseInt(this.textReaccionMinima.getText().trim()));
            Proyecto.getProyecto().setTiempoReaccionMaximo(Integer.parseInt(this.textReaccionMaxima.getText().trim()));
            if( (((Proyecto.getProyecto().getVelocidadMaxima() - Proyecto.getProyecto().getVelocidadMinima())<0)) || ( (Proyecto.getProyecto().getTiempoReaccionMaximo()-Proyecto.getProyecto().getTiempoReaccionMinimo())<0 )   ){
                JOptionPane.showMessageDialog(new JFrame(), "Velocidad o Tiempo de Reacción Invertidos ", "ERROR, CONFIGURACION DE DATOS", 1);
            }
            //CRISTIAN 07/08/2018 Estaba el siguiente if  NO ELSE IF como esta ahora
            else if (tamañox < 1 || tamañoy < 1){
                JOptionPane.showMessageDialog(new JFrame(), "Los campos Ancho y Alto deben ser mayores que '0' ", "ERROR, CONFIGURACION DE DATOS", 1);
            } 
            else{
                if (Proyecto.getProyecto().getTamañox() > tamañox || Proyecto.getProyecto().getTamañoy() > tamañoy){
                    String mensaje = "El nuevo tamaño de la grilla es distinto que el actualmente configurado 'ESTO PROVOCARA PERDIDA DE DATOS' ";
                    guardarCambios = JOptionPane.showConfirmDialog(new JFrame(), mensaje, "POSIBLE PERDIDA DE INFORMACION", 0, 2, null);
                }
                if(Proyecto.getProyecto().getTamañox() != tamañox || Proyecto.getProyecto().getTamañoy() != tamañoy){
                    redimensionarProyecto=true;
                }            
                if (guardarCambios == 0){
                    int cantidadCeldasX = (int)((double)tamañox / 0.4 + 1.0);
                    int cantidadCeldasY = (int)((double)tamañoy / 0.4 + 1.0);
                    //AutomataCelular ambiente=new AutomataCelular(cantidadCeldasX, cantidadCeldasY);
                    AutomataCelular ambiente=new AutomataCelular(cantidadCeldasY, cantidadCeldasX);
                    if(!((Proyecto.getProyecto().getTamañox()==0) || (Proyecto.getProyecto().getTamañoy()==0))){ //Proyecto Existente Debo REDIMENSIONARLO
                        for (int i = 0; i < Proyecto.getProyecto().getAc().getAlto(); ++i) {
                            for (int j = 0; j < Proyecto.getProyecto().getAc().getAncho(); ++j) {
                                ambiente.setCelda(i, j, Proyecto.getProyecto().getAc().getCelda(i, j));
                            }
                        }
                    }
                    Proyecto.getProyecto().setAc(ambiente);
                    Proyecto.getProyecto().setTamañox(tamañox);
                    Proyecto.getProyecto().setTamañoy(tamañoy);
                    
                    //CRISTIAN 07/08/2018 Comentados porquee saque los combos
                    //Proyecto.getProyecto().setPropagacionFuego(this.comboFuego.getSelectedIndex()+1);
                    //Proyecto.getProyecto().setPropagacionHumo(this.comboHumo.getSelectedIndex()+1);
                    Proyecto.getProyecto().setPropagacionFuego(1);
                    Proyecto.getProyecto().setPropagacionHumo(1);
                    //CRISTIAN 07/08/2018
                    
                    Proyecto.getProyecto().setNombreProyecto(this.textNombreProyecto.getText());
                    Proyecto.getProyecto().setNotasProyecto(this.textNotas.getText());  
                    if(redimensionarProyecto){
                        Proyecto.getProyecto().setProyectoValido(0);
                    }
                }
                VentanaPrincipal.getVentanaPrincipal().setEstadoMenuPrincipal(true,true,true);
                this.dispose();
                ventanaConfiguracionGeneral=null;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(new JFrame(), "Datos o formato incorrecto", "ERROR DE ENTADA DE DATOS", 1);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> comboVelMaxima;
    private javax.swing.JComboBox<String> comboVelMinima;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelRea;
    private javax.swing.JLabel labelReaccion;
    private javax.swing.JLabel labelValido;
    private javax.swing.JLabel labelVel;
    private javax.swing.JTextField textAltoY;
    private javax.swing.JTextField textAnchoX;
    private javax.swing.JTextField textNombreProyecto;
    private javax.swing.JTextArea textNotas;
    private javax.swing.JTextField textPersonas;
    private javax.swing.JTextField textReaccionMaxima;
    private javax.swing.JTextField textReaccionMinima;
    // End of variables declaration//GEN-END:variables


}
